# Generated by Django 3.1.7 on 2021-07-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mentor')),
            ],
        ),
    ]
