# Generated by Django 3.1.7 on 2021-07-25 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videocontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='mentor',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='mentor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
