# Generated by Django 3.1.7 on 2021-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocontent', '0002_auto_20210725_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='attendees',
            field=models.TextField(default=''),
        ),
    ]
